services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - db
    networks:
      - backend

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - backend

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: todo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - backend

volumes:
  redis-data:
  postgres-data:

networks:
  backend:
    driver: bridge
